strictness: high
test-warnings: true
doc-warnings: false
max-line-length: 120

ignore-patterns:
  - 'venv/*'
  - '.idea/*'
  - '.egg-info/*'
  - '__pycache__'
  - '.pytest_cache/*'

ignore-paths:
  - docs
  - .tox
  - venv

pyflakes:
  ignore: D203
  max-complexity: 10

mccabe:
  run: false
  options:
    max-complexity: 10

pep8:
  options:
    max-line-length: 120

pylint:
  disable:
    - line-too-long  # Already checked by pep8
    - 'logging-fstring-interpolation'
    - 'wrong-import-position'
    - 'wrong-import-order'
    - 'too-many-ancestors'